export default [
  {
    id: 1,
    image: "/images/1.jpg",
    name: "Book #1",
    category: "science",
    author: "Author Name",
    price: "100",
    pagesNo: "20",
    ISBN: "10",
    quantity: "10",
  },
  {
    id: 2,
    image: "/images/2.jpg",
    name: "Book #2",
    category: "science",
    author: "Author Name",
    price: "200",
    pagesNo: "50",
    ISBN: "20",
    quantity: "10",
  },
  {
    id: 3,
    image: "/images/3.jpg",
    name: "Book #3",
    category: "science",
    author: "Author Name",
    price: "300",
    pagesNo: "300",
    ISBN: "30",
    quantity: "10",
  },
  {
    id: 4,
    image: "/images/4.jpg",
    name: "Book #4",
    category: "science",
    author: "Author Name",
    price: "400",
    pagesNo: "100",
    ISBN: "40",
    quantity: "10",
  },
  {
    id: 5,
    image: "/images/5.jpg",
    name: "Book #5",
    category: "science",
    author: "Author Name",
    price: "500",
    pagesNo: "40",
    ISBN: "50",
    quantity: "10",
  },
  {
    id: 6,
    image: "/images/6.jpg",
    name: "Book #6",
    category: "science",
    author: "Author Name",
    price: "600",
    pagesNo: "600",
    ISBN: "60",
    quantity: "10",
  },
];
